### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by gadjet** [stephenkeep/node-red-contrib-amazondash#3]
Hi,
I installed this a while ago on my Pi3 and it worked well but I've been trying to load it on my Pi Zero W for a few days now and the install fails every time with an error saying it cannot access GITHUB
Debug log attached as well as the terminal output.
```
9 Mar 19:20:23 - [warn] Error: Command failed: npm install --production node-red-contrib-amazondash
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/mranney/node_pcap.git resetting remote /home/pi/.npm/_git-remotes/git-https-github-com-mranney-node-pcap-git-53ba2616 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/mranney/node_pcap.git /home/pi/.npm/_git-remotes/git-https-github-com-mranney-node-pcap-git-53ba2616: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/mranney/node_pcap.git /home/pi/.npm/_git-remotes/git-https-github-com-mranney-node-pcap-git-53ba2616: undefined
npm ERR! Linux 4.4.48+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production" "node-red-contrib-amazondash"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
```

[npm-debug.log.txt](https://github.com/stephenkeep/node-red-contrib-amazondash/files/832077/npm-debug.log.txt)

**Comment by tedstriker** [comment]
try `sudo apt-get update` and then `sudo apt-get install git`
